### ISSUE TITLE
renderer.resize does not resize diffuseTexture and normalsTexture

### ISSUE THREAD

**Issue by tststs** [pixijs/pixi-lights#11]
Hi there,

just played a bit with pixi-lights but after calling the resize method of the renderer it looks like this:

before:
![bildschirmfoto 2015-08-23 um 14 03 09](https://cloud.githubusercontent.com/assets/3591665/9428146/201e3958-49a0-11e5-8a02-fc47aadb4e30.png)

after:
![bildschirmfoto 2015-08-23 um 14 03 20](https://cloud.githubusercontent.com/assets/3591665/9428147/27f46710-49a0-11e5-8b17-fde6561d4045.png)

I fixed the problem by resizing `diffuseTexture`and `normalsTexture`.

```
resize: function (width, height)
    {
      PIXI.WebGLRenderer.prototype.resize.call(this, width, height);

      if (this.diffuseTexture && this.normalsTexture) {

        this.diffuseTexture.resize(width, height);
        this.normalsTexture.resize(width, height);
      }
    },
```

I don't know exactly if this solves the problem entirely and it surely could be made better than checking for `this.diffuseTexture && this.normalsTexture` so there is no pull request.

i did the check because `WebGLRenderer.prototype._initContext` calls the resize method before `this.diffuseTexture` and `this.normalsTexture` are instantiated.

greeting from berlin,
tststs

**Comment by ivanpopelyshev** [comment]
not a case for v4.
