### ISSUE TITLE
pixi v4 compatibility

### ISSUE THREAD

**Issue by cornop** [pixijs/pixi-lights#13]
Currently getting `Uncaught TypeError: Cannot read property 'registerPlugin' of undefined` with latest dev branch of pixi.

**Comment by englercj** [comment]
Yeah this was an experiment, never really got around to making it into a fully supported library. Probably won't take the time to upgrade it.

Accepting PRs though.

**Comment by Oza94** [comment]
@englercj so sad ! Thanks anyway this is great stuff to learn ! 

Have you used some specific resources to implement this lib? I'm far from your level (for PRs) but I want to learn how I can achieve this :)

**Comment by englercj** [comment]
I wrote a blog post on my journey of learning the techniques necessary and creating this experiment:

http://englercj.github.io/2016/01/03/pixi-deferred-lighting/

**Comment by hopewise** [comment]
What's the latest version of pixi to try this package?

**Comment by mw4ll4c3** [comment]
It should work against the latest PIXI 3.

**Comment by englercj** [comment]
> What's the latest version of pixi to try this package?

https://github.com/pixijs/pixi-lights/blob/master/package.json#L29

**Comment by hopewise** [comment]
Thank you

**Comment by finscn** [comment]
Is there any news about lights plugin for PIXI v4 ?

**Comment by ivanpopelyshev** [comment]
There was one, month or two ago - I know how to make it ompatible with pixi-display - you'll be able to add lights inside sprites or containers , and they'll be processed later when applying lightmap.. I didnt have time to implement it :(

**Comment by englercj** [comment]
> Is there any news about lights plugin for PIXI v4 ?

https://github.com/pixijs/pixi-lights/issues/13#issuecomment-216055982

**Comment by yhwh** [comment]
@ivanpopelyshev are you talking about another plugin ? if yes could you share a link please ?

**Comment by yhwh** [comment]
In fact nevermind just found it ! https://github.com/pixijs/pixi.js/issues/3360

**Comment by ivanpopelyshev** [comment]
Done.
