### ISSUE TITLE
How to implement the shadow like FOV ?

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-lights#15]
I want to create a game with  FOV (Field of vision/view ) and Fog Of War.

Like http://christmasexperiments.com/experiments/11  .
and
http://www.unwinnable.com/wp-content/uploads/2013/06/Monaco.jpg
https://7yrl.files.wordpress.com/2013/12/helives.png
http://www.playchilla.com/wp-content/uploads/2012/12/2d-shadows.png
http://i.imgur.com/B8g2o7b.jpg
http://lab.wx3.com/temp/screenshot01.jpg

Could pixi-light help me ?  How to implement  ? 

Thanks

P.S. :
 I know the  algorithm of FOV , and I could implement it on Canvas2D with hard-edge.
like this  https://camo.githubusercontent.com/88bfed3e14132b417d9f5c7d01bca0b9a803abf9/687474703a2f2f692e696d6775722e636f6d2f335371706942542e6a7067 . 

But I don't know how to create a FOV with soft-edges and  dynamic 2d lighting effect by Pixi.js

**Comment by englercj** [comment]
Raycasting is a common way of doing this: http://www.redblobgames.com/articles/visibility/

This lib doesn't implement shadows, but the experiment you linked does so that might be helpful as well.

**Comment by finscn** [comment]
I've read this article  two years ago and I said "I know the algorithm of FOV , and I could implement it on Canvas2D with hard-edge."
P.S. : the Raycasting is not a good way.

Whatever , thanks a lot.

**Comment by englercj** [comment]
Raycasting is the most common way of doing this. You raycasst, develop the results into geometry that you draw using the method I described.

**Comment by finscn** [comment]
this example : http://christmasexperiments.com/experiments/11    
Don't use this project ?

**Comment by englercj** [comment]
No it does not, it was written before this plugin was created and while it uses "deffered rendering" it is done in a more specific way to fullfill the requirements of the Christmas Experiment.

This library implements a simple deferred renderer and normal rendering.
