### ISSUE TITLE
stats block events

### ISSUE THREAD

**Issue by hopewise** [pixijs/pixi-lights#16]
I've just downloaded the repo, and tried to play with it, I've noticed that stats blocks events, thus, I can't add new lights or move the light when mouse move..

Fixed it by commenting those lines only in index.html:

stats.domElement.style.right = '0px';
stats.domElement.style.bottom = '0px';

**Comment by msqaddura** [comment]
This repo looks to be abandoned but this is here
[#17](https://github.com/pixijs/pixi-lights/pull/17 )

**Comment by ivanpopelyshev** [comment]
@msqaddura its alive again.
