### ISSUE TITLE
npm build:dev ? 

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-lights#19]
Am sorry am new with npm since hour, it my first try.
i succeed build a version but i get only de minified version ?
how i can get a dev version?
i try `npm run build:dev` but it now seem work
`stack Error: missing script: build:dev`
![image](https://user-images.githubusercontent.com/24865815/38139201-6651f20e-33fc-11e8-9b44-15b97a6a918c.png)

**Comment by ivanpopelyshev** [comment]
Powershell doesnt have "&&"

please type commands one-by-one

**Comment by djmisterjon** [comment]
ho ok the command was 
`npm run watch` instead for get the dev version.
