### ISSUE TITLE
current build broken?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-lights#2]
I just pulled the latest, built it, and browsed to http://localhost:8080

I get this error: `Uncaught TypeError: Cannot read property 'TRIANGLES' of undefined`

**Comment by ivanpopelyshev** [comment]
@englercj please update package.json : this version works only with latest pixi, not 3.0.2 and not 3.0.6 , but LATEST (you moved DRAW_MODES into const there)

**Comment by englercj** [comment]
Released pixi v3.0.7 and updated to that.

**Comment by mreinstein** [comment]
very nice, thanks! Still needs the actual `npm publish` step, and I'll update pixi-spine-lighting to point back at npm.
