### ISSUE TITLE
plans to push this to npm?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-lights#3]
right now it's not in npm I think.

**Comment by mreinstein** [comment]
I know this is still very much in flux and expirimental but even in it's current form it might helpful. I'm looking at this as part of a strategy to get dynamic lighting with spine via this prototype https://github.com/mreinstein/pixi-spine-lighting

**Comment by englercj** [comment]
I plan to push it into npm as soon as it is stable enough for use. Prior to that, just use a git url in your package.json
