### ISSUE TITLE
What is current state of light plugins?

### ISSUE THREAD

**Issue by kxmatejka** [pixijs/pixi-lights#44]
Hello guys, I'm completely lost. What is current state of the light plugins? Is it possible to achive something like this https://pixijs.io/pixi-lights/demo/index.html in pixi v5?

Thank you very much.

**Comment by SukantPal** [comment]
@bigtimebuddy We can always transfer issues within the PixiJS organization :)

**Comment by bigtimebuddy** [comment]
Did not know that! Thanks @SukantPal. I don't see that on the GH app. Will check it out on desktop.

**Comment by kxmatejka** [comment]
**So what I observed:**
- plugin works with pixi v4
- port to v5 is in the hands of a nondeterministic god #41 
- after all, maybe like me, you don't need full-blown lights for your 2d game, try to check masks this https://pixijs.io/examples/#/masks/filter.js
