### ISSUE TITLE
Is there an easy-ish way to mark a sprite as self-illuminating?

### ISSUE THREAD

**Issue by mreinstein** [pixijs/pixi-lights#5]
What I'd like to do is take a sprite or graphics object, mark it as self illuminating and give it a bloom effect filter. The idea being that a light source visually represented in the scene wouldn't be affected by lights/normals. kind of like this:

![self_illum_comparison](https://cloud.githubusercontent.com/assets/718067/8420054/c2821ab4-1e73-11e5-9fa4-d5d42a85e5f9.jpg)

**Comment by englercj** [comment]
Have you tried not setting the normal texture? Have you tried attaching a light to the object itself?

**Comment by mreinstein** [comment]
I tried disabling the normal texture yes. I also added a bloom filter to the object. I hadn't tried attaching a light to the object itself, which I'll do now.

**Comment by englercj** [comment]
I'm not sure there is a way in this lib to say "exclude this object from lighting effects".

**Comment by mreinstein** [comment]
> I'm not sure there is a way in this lib to say "exclude this object from lighting effects".

yeah that's exactly what I'm after. That's too bad. Thanks for the heads up anyway.

By the way this prototype is effin cool!  Great work so far. :)

**Comment by mreinstein** [comment]
I just thought of a workaround, figured I'd get your 2 cents; would it be feasible to declare a standard pixi renderer, use that for rendering just the self illuminated stuff, and draw it on top of the deferred render?

**Comment by englercj** [comment]
If you have a separate renderer then that is a separate canvas, so I don't think that is a great idea.

Likely this lib would have to have a post-render step that renders all the non-illuminated objects.

**Comment by mreinstein** [comment]
https://www.bountysource.com/issues/23334687-is-there-an-easy-ish-way-to-mark-a-sprite-as-self-illuminating

**Comment by englercj** [comment]
Ok, so I added an "unlit" render pass for after the scene is drawn. Any sprites without a normal texture assigned will act like an unlit sprite and be drawn on top of the lit scene.

I added an example of this in the index.html file, so you can view it by cloning the repo, running `npm i`, then `npm start`.

**Comment by mreinstein** [comment]
I've tried it out, works great! I'm assuming this panda test object is unlit by the lighting engine, I'd be able to attach shaders to it as normal?

**Comment by mreinstein** [comment]
Sorry, I didn't read the source carefully enough; I see now that you're actually already applying a filter to the panda image. Great work!
